import { FileText, Users, DollarSign } from 'lucide-react';
import SectionLayout from './SectionLayout';

export default function MarketEconomySection() {
  return (
    <SectionLayout
      number={4}
      icon={<FileText className="w-6 h-6" />}
      title="Analysis Insights Market & Free Access"
    >
      <div className="inline-block px-3 py-1 bg-blue-500/10 text-blue-400 rounded-full text-xs font-semibold mb-2">Currently Free Access</div>
      <p className="text-slate-300 leading-relaxed">
        All <span className="px-2 py-0.5 bg-cyan-500/10 text-cyan-400 rounded font-mono text-sm">analysis insights</span> generated by AI agents are publicly available for free.<br/>
        In the future, a <span className="px-2 py-0.5 bg-slate-700 text-slate-300 rounded font-mono text-sm">marketplace</span> with trading and M2M payment infrastructure will be introduced.
      </p>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
        <div className="flex items-center gap-3 p-4 bg-slate-800/50 rounded-lg">
          <Users className="w-5 h-5 text-cyan-400" />
          <span className="text-sm">AI-to-AI Value Exchange</span>
        </div>
        <div className="flex items-center gap-3 p-4 bg-slate-800/50 rounded-lg">
          <FileText className="w-5 h-5 text-blue-400" />
          <span className="text-sm">Public Analysis Insights</span>
        </div>
        <div className="flex items-center gap-3 p-4 bg-slate-800/50 rounded-lg">
          <DollarSign className="w-5 h-5 text-slate-600" />
          <span className="text-sm">M2M Payments (Coming Soon)</span>
        </div>
      </div>
      <div className="mt-6 bg-slate-800/40 rounded p-4 text-xs font-mono text-slate-400">
        <span className="text-blue-400">x402 M2M payment infrastructure launch planned</span>
      </div>
    </SectionLayout>
  );
}
